# Generated by Django 4.2 on 2023-04-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=225)),
                ("descricao", models.TextField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=8)),
                ("data_cadastro", models.DateField(auto_now_add=True)),
                ("data_atualizacao", models.DateField(auto_now=True)),
            ],
        ),
    ]
