# Generated by Django 4.2 on 2023-04-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categorias", "0002_remove_categoria_produtos"),
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="categorias",
            field=models.ManyToManyField(
                related_name="produtos", to="categorias.categoria"
            ),
        ),
    ]
