# Generated by Django 4.2 on 2023-04-19 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0002_produto_categorias"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="categorias",
        ),
    ]
