# Generated by Django 4.2 on 2023-04-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=225)),
                (
                    "produtos",
                    models.ManyToManyField(
                        related_name="categorias", to="produtos.produto"
                    ),
                ),
            ],
        ),
    ]
