# Generated by Django 4.2 on 2023-04-19 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("categorias", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoria",
            name="produtos",
        ),
    ]
