# Generated by Django 4.2 on 2023-04-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0003_remove_produto_categorias"),
        ("categorias", "0002_remove_categoria_produtos"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="produtos",
            field=models.ManyToManyField(
                related_name="categorias", to="produtos.produto"
            ),
        ),
    ]
